### ISSUE TITLE
Lost file D4JMeta.csv

### ISSUE THREAD

**Issue by ToolmanInside** [ASSERT-KTH/SelfAPR#5]
Hi, I am trying to run script `3_prepare_test_data.py`, but I found `scripts/D4JMeta.csv` used in line 46 is not provided.

**Comment by galaxyview** [comment]
Me too.

**Comment by SophieHYe** [comment]
Hi, thanks for pointing this out! I have added scripts/D4JMeta.csv here  (maybe not the latest version), but please check!
