### ISSUE TITLE
About file SelfAPR.csv

### ISSUE THREAD

**Issue by lemon1-ui** [ASSERT-KTH/SelfAPR#6]
Hi Dr. Ye, sorry to bother you. When I run train.py, I get a data format mismatch error: pandas.errors.ParserError: Error tokenizing data. c error: Expected 1 fields in line 3, saw 2, is additional processing required here? I would be very grateful if you can reply. Thanks a lot in advance!

**Comment by SophieHYe** [comment]
Hi @lemon1-ui 

It is normal to get mismatch error when loading csv files. You can simply configure a parameter to ignore the mismatch lines and it would work :)

**Comment by lemon1-ui** [comment]
&nbsp; &nbsp; &nbsp; &nbsp;Hi, Dr. Ye. I sincerely appreciate you, I will try it again. Sorry to bother you but I have some issues about ITER, may I ask some questions?&nbsp;I would be very grateful if you can reply. Thanks a lot in advance!




?柠檬不萌
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ASSERT-KTH/SelfAPR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月1日(星期一) 上午10:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ASSERT-KTH/SelfAPR] About file SelfAPR.csv (Issue #6)





 
Hi @lemon1-ui
 
It is normal to get mismatch error when loading csv files. You can simply configure a parameter to ignore the mismatch lines and it would work :)

**Comment by lemon1-ui** [comment]
Hi, Dr. Ye. I sincerely appreciate you, I will try it again. Sorry to bother you but I have some issues about ITER, may I ask some questions?I would be very grateful if you can reply. Thanks a lot in advance!
